FROM alpine:latest

# Point to specific Alpine Package repositories for Chromium and Firefox.
RUN apk update && apk upgrade \
    && echo @latest-stable http://nl.alpinelinux.org/alpine/latest-stable/community >> /etc/apk/repositories \
    && echo @latest-stable http://nl.alpinelinux.org/alpine/latest-stable/main >> /etc/apk/repositories \
    && echo @edge-testing http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories \
    && echo @edge-main http://dl-cdn.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories

# Install Ruby dev environment
RUN apk add --no-cache build-base
RUN apk add --no-cache libffi-dev
RUN apk add --no-cache ruby-dev
RUN apk add --no-cache ruby-rdoc
RUN apk add --no-cache ruby-webrick@latest-stable
RUN apk add --no-cache zlib-dev

# Install Chromium
RUN apk add --no-cache chromium-chromedriver
RUN apk add --no-cache chromium@latest-stable
RUN apk add --no-cache harfbuzz@latest-stable
RUN apk add --no-cache nss@latest-stable

# Install Ruby gems required by the test framework.
RUN gem install rake
RUN gem install minitest
RUN gem install minitest-reporters
RUN gem install watir
RUN gem install twilio-ruby
RUN gem install webdriver-user-agent
RUN gem install headless
RUN gem install selenium-webdriver

# Clean up leftovers to help keep the final image small.
RUN rm -rf /var/lib/apt/lists/* \
    /var/cache/apk/* \
    /usr/share/man \
    /tmp/*

#Add local file
COPY auto_everything.rb ./home/

# Add 'webdriver' as a user
#RUN adduser -D webdriver 

# Switch to non-privileged user 'webdriver'
#USER webdriver

# Set the environment variables for the Chromium browser.
ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/
